web:
  image: gauravgoyal/apache2-mpm-php5-fpm
  ports:
    - "8080:80"
  volumes:
    - /home/virus/Drupal/code/:/var/www/html/
    - /home/virus/Drupal/sites-available/:/etc/apache2/sites-available/
    - /home/virus/Drupal/sites-enabled/:/etc/apache2/sites-enabled/
  environment:
    - AUTHORIZED_KEYS="Your key"
  links:
    - db
db:
  image: tutum/mysql
  volumes:
    - /home/virus/Drupal/mysql:/var/lib/mysql
  environment:
    - MYSQL_PASS=test
    - MYSQL_USER=admin

