web:
  image: gauravgoyal/apache2-mpm-php5-fpm:mac
  ports:
    - "8080:80"
    - "8022:22"
  volumes:
    - ~/public_html/code:/var/www/html/
    - ~/public_html/sites-available:/etc/apache2/sites-available/
    - ~/public_html/sites-enabled:/etc/apache2/sites-enabled/
    - ~/public_html/logs:/var/log/apache2/
  environment:
    - AUTHORIZATION_KEYS=your key
  links:
    - db
    - memcached
db:
  image: gauravgoyal/mysql:mac
  volumes:
    - ~/public_html/mysql:/var/lib/mysql/
  environment:
    - MYSQL_ADMIN_PASS=admin
    - MYSQL_USER_NAME=drupal
    - MYSQL_USER_DB=drupal
    - MYSQL_USER_PASS=drupal 
memcached:
  image: gauravgoyal/memcached:latest
